### PR TITLE
Added scripts for the rest of the GoldSrc Steam games

### LINKED ISSUE #240: [HL:Opposing Force/Ricochet] Creation
Could support be added for the rest of the Steam GoldSrc Engine based games? Like Opposing Force, HLDM, and Ricochet (well if you really want to do that one).

### PR DESCRIPTION
**Pull request by Xylemon**
This should fix #240 however, I did have problems getting the mods to actually download. Perhaps the problem is related to #274.

### CODE REVIEW

**Comment by dgibbs64** [comment]
Great work. Just a question about HL:DMC I already have a server called Half Life: Deathmatch classic. mine says valve and yours dmc. Whats the difference?

**Comment by Xylemon** [comment]
The one you have with the "valve" folder is actually regular Half-Life multiplayer. Deathmatch Classic or "dmc" is a port of Quake by Valve to GoldSrc. You should change the HalfLifeDeathmatchClassic folder to just HalfLifeDeathmatch.

**Comment by dgibbs64** [comment]
Thanks for the heads up I will modify my scripts and merge yours. Thanks for your submission. Code submissions are always welcome.

**Comment by Xylemon** [comment]
No problem, I'll probably contribute some more soon enough here.

**Comment by dgibbs64** [comment]
Looks like we are only missing Half-Life Deathmatch: Source Dedicated server now and we have the complete set. If you could create that one it would be very helpful.

**Pull request merged**
